---
# tasks file for sa-dev-phpstorm
  - include: tasks_java.yml
    when: option_install_java

  - include: tasks_elastic_search.yml
    when: option_install_elastic_search

  - include: tasks_graylog.yml

  - include: tasks_graylog_nginx.yml
    when: option_nginx_frontend
