---
  - name: ElasticSearch | Install python-pycurl
    apt: pkg=python-pycurl state=installed
    become: yes
    tags:
      - es

  - name: ElasticSearch | Add GPG key to apt keyring
    apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present
    become: yes
    tags:
      - es

  - name: ElasticSearch | Add Debian apt repository
    apt_repository: repo="deb https://packages.elastic.co/elasticsearch/2.x/debian stable main" state=present update_cache=yes
    become: yes
    tags:
      - es

  - name: ElasticSearch | Install
    apt: update-cache=yes pkg=elasticsearch state=latest
    become: yes
    tags:
      - es

  - name: ElasticSearch | Create log and data folders
    file: path={{item}} state=directory owner=elasticsearch group=elasticsearch
    with_items:
      - "/var/log/elasticsearch"
      - "/var/data/elasticsearch"
    become: yes
    tags:
      - es


  - name: ElasticSearch | Restart
    action: service name=elasticsearch state=restarted enabled=yes
    become: yes
    tags:
      - es

  - name: ElasticSearch | Install plugins
    command: /usr/share/elasticsearch/bin/plugin --install {{item.plugin}} creates=/usr/share/elasticsearch/plugins/{{item.name}}/_site/.gitignore
    with_items: '{{elasticsearch_plugins}}'
    when: elasticsearch_plugins is defined
    become: yes
    tags:
      - es
