---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-nginx"
       }
     - {
         role: "sa-graylog",
         graylog_api_domain: "{{graylog_domain}}",
         option_install_java: true,
         option_install_elastic_search: true,
         option_nginx_frontend: true
       }


  tasks:
    - debug: msg="Tasks section"
