---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-graylog",
         option_install_java: true,
         option_install_elastic_search: true 
       }


  tasks:
    - debug: msg="Tasks section"
